simulated_motors:
  - "/hrim_actuator_rotaryservo_000000000001/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_000000000001/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000002/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000002/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_000000000003/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000003/trajectory_axis2"

simulated_gripper:
  - "/hrim_actuator_gripper_000000000004/fingerstate"
  - "/hrim_actuator_gripper_000000000004/fingercontrol"

real_motors:
  - "/hrim_actuator_rotaryservo_70B3D521A042/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_70B3D521A042/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A08A/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A08A/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_70B3D521A0A4/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A0A4/trajectory_axis2"

real_gripper:
  - "/hrim_actuator_gripper_000A35000144/fingerstate"
  - "/hrim_actuator_gripper_000A35000144/fingercontrol"
